spring:
  application:
    name: order
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
  # 暴露服务信息到adminServer 需要先启动 adminServer
  boot:
    admin:
      client:
        #adminServer 地址
        url: http://localhost:20070

  # zipkin-server 地址 需要启动 zipkin-server
  zipkin:
    base-url: http://localhost:9411/
    sender:
      #请求方式,默认以http的方式向zipkin server发送追踪数据
      type: web
  sleuth:
    async:
      enabled: true
#    # When true, generate 128-bit trace IDs instead of 64-bit ones.
    traceId128: true
    sampler:
      #Sleuth的抽样收集概率
      probability: 1.0

  cloud:
    loadbalancer:
      ribbon:
        enabled: true

#默认暴露所有的节点给 adminServer 生产上谨慎使用 可增加认证
management:
  endpoints:
    web:
      exposure:
        #暴露hystrix监控端点 hystrix.stream
        include: '*'
  endpoint:
    health:
      show-details: always


# 添加开启admin的日志监控
logging:
  file:
    name: order.log