spring:
  application:
    name: gateway
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
            # spring.cloud.gateway.discovery.locator.enabled为true，
            # 表明gateway开启服务注册和发现的功能，并且spring cloud gateway
            # 自动根据服务发现为每一个服务创建了一个router，这个router将以服务名
            # 开头的请求路径转发到对应的服务。
            # spring.cloud.gateway.discovery.locator.lowerCaseServiceId是将请求路径上的服务名
            # 配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），
            # 比如以/order/*的请求路径被路由转发到服务名为order的服务上。
          enabled: false
          lowerCaseServiceId: true
      routes:
        # 在上面的配置中，配置了一个Path 的predict,将以/order/**开头的请求都会转发到uri为lb://ORDER的地址上，
        # lb://ORDER 即ORDER服务的负载均衡地址，并用StripPrefix的filter 在转发之前将/order去掉。
        # 同时将spring.cloud.gateway.discovery.locator.enabled改为false，
        # 如果不改的话，之前的localhost:8081/service-hi/hi?name=1323这样的请求地址也能正常访问，因为这时为每个服务创建了2个router。
        - id: ORDER
          uri: lb://ORDER
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: goods
          uri: http://127.0.0.1:20050
          predicates:
            - Path=/goods/**
          filters:
            - name: RequestRateLimiter
              args:
                # 使用SpEL从容器中获取对象
                key-resolver: '#{@pathKeyResolver}'
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                X-RateLimit-Replenish-Rate: 1
                X-RateLimit-Burst-Capacity: 3
                # 令牌桶的总容量
                redis-rate-limiter.burstCapacity: 3
            - RewritePath=/goods/(?<segment>.*), /$\{segment}
           # 配置转发路径去掉项目后缀 例如/goods/**  使用如下方式 或者 上面 RewritePath方式
#          filters:
#            - StripPrefix=1
  #zipkin server地址
  zipkin:
    base-url: http://localhost:9411
    sender:
      #请求方式,默认以http的方式向zipkin server发送追踪数据
      type: web
  sleuth:
    async:
      enabled: true
    sampler:
      #采样的百分比 这些是全部采样 生产上看需求配置
      probability: 1.0

  #redis 地址 显示 redis限流
  redis:
    port: 7001
    host: localhost

# 添加开启admin的日志监控
logging:
  level:
    cn.itcast.order.fegin.ProductFeginClient: debug
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

