spring:
  application:
    name: bus
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
  cloud:
    # bus 配置
    bus:
      enabled: true
      trace:
        enabled: true
  #mq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#默认暴露所有的节点给 adminServer 生产上谨慎使用 可增加认证
management:
  endpoints:
    web:
      exposure:
        #暴露hystrix监控端点 hystrix.stream bus-refresh
        include: '*'
  endpoint:
    health:
      show-details: always


# 添加开启admin的日志监控
logging:
  file:
    name: bus.log